

#controller_manager:
#  ros__parameters:
#    update_rate: 50
#    use_sim_time: true

#    joint_state_broadcaster:
#      type: joint_state_broadcaster/JointStateBroadcaster

#    coupler_joint_position_controller:
#      type: position_controllers/JointPositionController
#      joint: robot0_1_revolute_joint_robot_to_coupler

#    fixed_joint_position_controller:
#      type: position_controllers/JointPositionController
#      joint: robot0_1_revolute_joint_coupler_to_fixed
