controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true#

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: ${prefix}base_link

    left_wheel_names: ['${prefix}left_wheel_joint']
    right_wheel_names: ['${prefix}right_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false


#controller_manager:
#  ros__parameters:
#    update_rate: 50
#    use_sim_time: true

#    joint_state_broadcaster:
#      type: joint_state_broadcaster/JointStateBroadcaster

#    coupler_joint_position_controller:
#      type: position_controllers/JointPositionController
#      joint: robot0_0_revolute_joint_robot_to_coupler

#    fixed_joint_position_controller:
#      type: position_controllers/JointPositionController
#      joint: robot0_0_revolute_joint_coupler_to_fixed
